initialize_particle_ensemble()
io.write("The particle ensemble has been initialized\n")
io.write("There are currently ", get_num_particles(), " particles in the system\n")
add_particle(1,2.14,316.78)
add_particle(0.0,-12,40)
io.write("But now there are ", get_num_particles(), " particles in the system\n")
